name: Ejecutar proyecto

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: http://docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - run: docker build -t imagem-melicia_mendez_devops:latest .

      - run: docker tag imagem-melicia_mendez_devops:latest meliciatenis/imagem-melicia_mendez_devops:teste
        
      - run: docker push meliciatenis/imagem-melicia_mendez_devops:teste

  deploy-job:
 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2