name: Ejecutar proyecto

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-job:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:dind
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2
      - name: Build and push Docker image
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker build -t imagem-melicia_mendez_devops:latest .
          docker tag imagem-melicia_mendez_devops:latest meliciatenis/imagem-melicia_mendez_devops:teste
          docker login --username meliciatenis --password $DOCKER_PASSWORD docker.io
          docker push meliciatenis/imagem-melicia_mendez_devops:teste

  deploy-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2
