name: Ejecutar proyecto

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-job:
    runs-on: docker-20
    steps:
      - name: Checkout del repositorio
      - uses: actions/checkout@v2
      - run: docker build -t imagem-melicia_mendez_devops:latest .
      - run: docker tag imagem-melicia_mendez_devops:latest meliciatenis/imagem-melicia_mendez_devops:teste
      - run: |
          docker login --username meliciatenis --password ${{ secrets.DOCKER_PASSWORD }} docker.io
          docker push meliciatenis/imagem-melicia_mendez_devops:teste

  deploy-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2