name: Ejecutar projeto
on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2


  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Build and push Docker image
        uses: docker/compose-action@v2
        with:
          compose-file: docker-compose.yml
          services: my-service
          command: push
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  
  deploy-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2
